version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: my_website_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_website_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/migrations
      - ./seeders:/docker-entrypoint-initdb.d/seeders
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: my_website_redis
    restart: always
    ports:
      - "6379:6379"